---
title: 'Alex/Trevor Bird Abundance Data: K=4'
author: "Kushal K Dey"
date: "April 18, 2016"
output: 
  html_document:
    css: floating-toc.css
    toc: true
---

## Overview

We apply deeptpx model on Alex/Trevor bird abundance data. We perform the deeptpx model for $4$ topics at the bottom layer and $2$ topics at the top layer (so total 2 layers of topics).

## Data Preparation

```{r echo=TRUE, eval=TRUE, warning=FALSE, message=FALSE}
library(HimalayanBirdsAbundance)
data("HimalayanBirdsAbundance")
new_counts <- t(exprs(HimalayanBirdsAbundance));
metadata <- pData(HimalayanBirdsAbundance);

elevation_metadata=metadata$Elevation;
east_west_dir = metadata$WorE;

bodymass_data <- read.csv('../external_data/massKushal.csv');

bodymass_val <- bodymass_data[,2];
bodymass_birds <- bodymass_data[,1];

bodymass_matched <- bodymass_data[match(colnames(new_counts),bodymass_birds),2];
summary(bodymass_matched)

ordered_counts <- new_counts[,order(bodymass_matched, decreasing = FALSE)];

```

## deeptpx application

```{r}
topic_clus <- maptpx::topics(ordered_counts, K=4, tol=0.0001);
docweights <- topic_clus$omega
theta <- topic_clus$theta
```

### topic model K=4

```{r echo=TRUE, eval=TRUE, fig.height=5, fig.width=8, message=FALSE, warning=FALSE}
K <- 4
par(mfrow=c(1,1))
east_west_elevation = paste0(metadata$WorE, "_", metadata$Elevation);

index1 <- which(metadata$WorE=="E");
index2 <- which(metadata$WorE=="W");
elevation1 <- metadata$Elevation[index1]; elevation2 <- metadata$Elevation[index2];
index_WE <- c(index1[order(elevation1)], index2[order(elevation2)]);

    barplot(t(docweights[index_WE,]),col=2:(K+1),axisnames=F,space=0,border=NA,main=paste("No. of clusters=",3),las=1,ylim=c(0,1),cex.axis=1.5,cex.main=1.4)

    combo_patch_dir = paste0(east_west_elevation);
    combo_patch_dir_ordered = combo_patch_dir[index_WE];

  match_labs=match(unique(combo_patch_dir_ordered),combo_patch_dir_ordered);
  match_labs_suffix=c(match_labs[2:length(unique(combo_patch_dir_ordered))],35);
  match_labs_prefix=match_labs[1:(length(unique(combo_patch_dir_ordered)))];
  labs=match_labs_prefix + 0.5*(match_labs_suffix - match_labs_prefix);

  axis(1,at=labs,unique(combo_patch_dir_ordered),las=2);
  abline(v=match_labs[2:length(match_labs)]);
```

### metatopic for K=3

```{r echo=TRUE, eval=TRUE}
libsize_birds <- rowSums(ordered_counts);

omega_1 <- topic_clus$omega
theta_1 <- topic_clus$theta

lambda_1 <- sweep(omega_1, 1, libsize_birds, "*");

z_level_1 <- array(0,c(dim(lambda_1)[1], dim(theta_1)[1], dim(lambda_1)[2]));
for(k in 1:dim(theta_1)[2]){
  z_level_1[,,k] <- floor(lambda_1[,k]%*%t(theta_1[,k]))
}

z_level_1_counts <- apply(z_level_1, c(1,3), sum);
```

```{r echo=TRUE, eval=TRUE}
topic_clus <- maptpx::topics(z_level_1_counts, K=3, tol=0.0001);
docweights <- topic_clus$omega
theta <- topic_clus$theta
```

```{r echo=TRUE, eval=TRUE, fig.height=5, fig.width=8, message=FALSE, warning=FALSE}
K <- 3
par(mfrow=c(1,1))
east_west_elevation = paste0(metadata$WorE, "_", metadata$Elevation);

index1 <- which(metadata$WorE=="E");
index2 <- which(metadata$WorE=="W");
elevation1 <- metadata$Elevation[index1]; elevation2 <- metadata$Elevation[index2];
index_WE <- c(index1[order(elevation1)], index2[order(elevation2)]);

    barplot(t(docweights[index_WE,]),col=2:(K+1),axisnames=F,space=0,border=NA,main=paste("No. of clusters=",3),las=1,ylim=c(0,1),cex.axis=1.5,cex.main=1.4)

    combo_patch_dir = paste0(east_west_elevation);
    combo_patch_dir_ordered = combo_patch_dir[index_WE];

  match_labs=match(unique(combo_patch_dir_ordered),combo_patch_dir_ordered);
  match_labs_suffix=c(match_labs[2:length(unique(combo_patch_dir_ordered))],35);
  match_labs_prefix=match_labs[1:(length(unique(combo_patch_dir_ordered)))];
  labs=match_labs_prefix + 0.5*(match_labs_suffix - match_labs_prefix);

  axis(1,at=labs,unique(combo_patch_dir_ordered),las=2);
  abline(v=match_labs[2:length(match_labs)]);
```


### metatopic for K=2

```{r echo=TRUE, eval=TRUE}
libsize_birds <- rowSums(z_level_1_counts);

omega_2 <- topic_clus$omega
theta_2 <- topic_clus$theta

lambda_2 <- sweep(omega_2, 1, libsize_birds, "*");

z_level_2 <- array(0,c(dim(lambda_2)[1], dim(theta_2)[1], dim(lambda_2)[2]));
for(k in 1:dim(theta_2)[2]){
  z_level_2[,,k] <- floor(lambda_2[,k]%*%t(theta_2[,k]))
}

z_level_2_counts <- apply(z_level_2, c(1,3), sum);
```

```{r echo=TRUE, eval=TRUE}
topic_clus <- maptpx::topics(z_level_2_counts, K=2, tol=0.0001);
docweights <- topic_clus$omega
theta <- topic_clus$theta
```

```{r echo=TRUE, eval=TRUE, fig.height=5, fig.width=8, message=FALSE, warning=FALSE}
K <- 2
par(mfrow=c(1,1))
east_west_elevation = paste0(metadata$WorE, "_", metadata$Elevation);

index1 <- which(metadata$WorE=="E");
index2 <- which(metadata$WorE=="W");
elevation1 <- metadata$Elevation[index1]; elevation2 <- metadata$Elevation[index2];
index_WE <- c(index1[order(elevation1)], index2[order(elevation2)]);

    barplot(t(docweights[index_WE,]),col=2:(K+1),axisnames=F,space=0,border=NA,main=paste("No. of clusters=",3),las=1,ylim=c(0,1),cex.axis=1.5,cex.main=1.4)

    combo_patch_dir = paste0(east_west_elevation);
    combo_patch_dir_ordered = combo_patch_dir[index_WE];

  match_labs=match(unique(combo_patch_dir_ordered),combo_patch_dir_ordered);
  match_labs_suffix=c(match_labs[2:length(unique(combo_patch_dir_ordered))],35);
  match_labs_prefix=match_labs[1:(length(unique(combo_patch_dir_ordered)))];
  labs=match_labs_prefix + 0.5*(match_labs_suffix - match_labs_prefix);

  axis(1,at=labs,unique(combo_patch_dir_ordered),las=2);
  abline(v=match_labs[2:length(match_labs)]);
```
